# This workflow will send notification about new releases in selected telegram chats

name: Telegram notifications

on:
  release:
    types: [created]

jobs:
  telegram-bot:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
        
    - name: Clone repo, install requirements
      run: |
        git clone https://github.com/v1a0/telegram-notify-workflow.git ./telegram-notify-workflow
        cd telegram-notify-workflow
        python -m pip install -r requirements.txt
        
    - name: Run bot
      env:
        secrets.WF_API_TOKEN: ${{ secrets.WF_API_TOKEN }}
        secrets.WF_CHAT_IDS: ${{ secrets.WF_CHAT_IDS }}
        secrets.WF_REPO: "v1a0/sqllex"
      run: |
        cd telegram-notify-workflow
        python bot.py --action release
